title:  Aly Kea # your name (or website title) here
logo: "/images/AvatarMaker.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Google Certified Data Analyst. Experience in R, SQL, Excel, and Tableau.
  <br><br>
  <br><br>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
